#!/usr/bin/env python3
"""
Admin configuration with hardcoded admin accounts.
Passwords are pre-hashed for security.

IMPORTANT: Replace these placeholder hashes with real ones generated by generate_admin_hashes.py
"""

# Hardcoded admin accounts - passwords are pre-hashed
# TODO: Replace these with real hashes from generate_admin_hashes.py
ADMIN_ACCOUNTS = [
    {'username': 'MCMINIBOTS ADMIN', 'email': 'admin.mcminibots@gmail.com', 'password_hash': 'scrypt:32768:8:1$QksAeOXW3k83mtJL$2dc88d8017b907c8c584b49a5d6498cbc156b4f09c386df29ca9ab469c584e8d88408d9acf7d9906e7411bf3ae576db05ab52da90e332859e937f294e83f4655'},
    {'username': 'Ryan Zhu Admin', 'email': 'zhuryan917@gmail.com', 'password_hash': 'scrypt:32768:8:1$d1x9pzUDVOocHgYZ$68354958c5b01fd8a376150a8cadc83df8cc3a6134abbee846f454174d02208e19c6190d83ad1b905f20cf39d4342d2dc21320d5242eb4d27063f75bc82ed254'}
]

def get_admin_accounts():
    """Get the list of admin accounts."""
    return ADMIN_ACCOUNTS

def is_admin_email(email):
    """Check if an email belongs to an admin account."""
    return any(admin['email'] == email for admin in ADMIN_ACCOUNTS)

def get_admin_by_email(email):
    """Get admin account by email."""
    for admin in ADMIN_ACCOUNTS:
        if admin['email'] == email:
            return admin
    return None